# Generated by Django 4.0.4 on 2022-04-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ordereditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderedItem',
        ),
    ]
