# Generated by Django 4.0.4 on 2022-04-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_order_client_address_order_client_phone_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expected_arrival',
            field=models.DateField(blank=True, null=True),
        ),
    ]
