# Generated by Django 4.0.4 on 2022-04-26 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order_expected_arrival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item'),
        ),
    ]
