# Generated by Django 4.0.4 on 2022-04-26 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_ordereditem_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereditem',
            old_name='item_id',
            new_name='item',
        ),
    ]
